---
- name: Install MySQL packages
  yum: name={{ item }} state=installed
  with_items:
  - MySQL-python
  - mysql
  - mysql-community-server

- name: Create Mysql configuration file
  template: src=my.cnf.j2 dest=/root/.my.cnf

- name: service mysql
  action: service name=mysqld state=started

- name: Create Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify:
  - restart mysql

- name: Change root user password on first run
  mysql_user: login_user=root
              login_password=''
              name=root
              password={{ mysql_root_password }}
              priv=*.*:ALL,GRANT
              host={{ item }}
  with_items:
  - "{{ ansible_hostname }}"
  - 127.0.0.1
  - ::1
  - localhost

- name: Remove the MySQL test database
  mysql_db: db=test state=absent

- name: Create databases
  mysql_db: name={{ item }} state=present collation=utf8_general_ci encoding=utf8
  with_items:
  - db1
  - db2

- name: delete anonymous MySQL server user for localhost
  mysql_user: user="" state="absent"

- name: Restart the MySQL service
  service: name=mysqld state=restarted enabled=true
